global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 0.5
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: True
      footprint: "[ [0.3,-0.15], [0.3,0.15], [0.225,0.15], [0.225,0.5], [-0.225, 0.5], [-0.225, 0.15], [-0.3,0.15], [-0.3, -0.15] ]"
      resolution: 0.05
      track_unknown_space: False
      plugins: ["static_layer", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: False
        subscribe_to_updates: True
        map_topic: /map
        enabled: True
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.55
        enabled: True
      always_send_full_costmap: True
  global_costmap_client:
    ros__parameters:
      use_sim_time: True
  global_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: True

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: odom
      robot_base_frame: base_link
      use_sim_time: True
      rolling_window: true
      width: 6.0
      height: 6.0
      resolution: 0.05
      footprint: "[ [-0.15, 0.3], [0.15,0.3], [0.15,0.225], [0.5,0.225], [0.5,-0.225], [0.15,-0.225], [0.15,-0.3], [-0.15,-0.3] ]"
      plugins: ["static_layer", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: False
        map_topic: /map
        enabled: True
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.55
        enabled: True
      always_send_full_costmap: True
